ls -lコマンドの実装
Hombo-Yasutaka/ruby-practices pull request #7
Opened 2023-06-30 01:25 UTC by Hombo-Yasutaka

2023-06-30 11:56 UTC, u1tnk requested changes

2023-06-30 11:56 UTC, u1tnk commented on 07.ls_object/ls.rb
> +    if file_info.symlink?
symlinkも対応してるんですね 👍

2023-07-03 01:16 UTC, Hombo-Yasutaka commented on 07.ls_object/ls.rb
> +  max_widths = Array.new(7, 0)
.timesに修正してrubocopを実行したら、以下の指摘がありました。
```
ls.rb:88:3: C: [Correctable] Performance/TimesMap: Use Array.new(7) with a block instead of .times.map.
  7.times.map do |column| ...
```
この場合、どちらを優先すればいいでしょうか？？

2023-07-04 00:28 UTC, Hombo-Yasutaka commented on 07.ls_object/ls.rb
> +  max_widths = Array.new(7, 0)
ありがとうございます！
今回はrubocopにしたがいます🫡

2023-07-04 15:03 UTC, u1tnk commented on 07.ls_object/ls.rb
> +  max_widths = Array.new(7, 0)
今気づきましたが、`Performance/TimesMap`とPerformanceカテゴリ なので読みやすいからというより速いからなんですね。
`7.times.map`の方が読みやすいとは思うけど、速いからなら納得。

2023-07-04 15:05 UTC, u1tnk approved these changes
ls_objectの方どうしようかなと思いましたが、lsコマンド1からここを使ってるんですよね。
今回はこれで良いので最終版のプラクティスの ls5 では 07から消すようにしてください 🙏

2023-07-05 01:47 UTC, merged